### ISSUE TITLE
Update README. 

### ISSUE THREAD

**Issue by EmanuelGF** [EmanuelGF/template-react-ui#18]
The folder structure info on the README file needs to be updated with the newly created cypress folders. 

Potential solvers:
@inezabonte
@BillNas

**Comment by inezabonte** [comment]
I'd love to take it

**Comment by inezabonte** [comment]
@EmanuelGF If I get this right. I'm supposed to create the folder structure similar to the one used for the src folder and add it to the README?
Where exactly should I add it?

**Comment by EmanuelGF** [comment]
Hi @inezabonte 
The cypress folder lives on the root of the project and so does the src. I think its better if you can recreate the folder structure you edited the last time and start from the root then cypress and src with their respective subfolders.
let me know if you need any further help.

**Comment by inezabonte** [comment]
Should I make a continuous structure with both src and cypress
or
Should I separate them

**Comment by EmanuelGF** [comment]
You can edit something like this:

Folder structure on root directory:
```
.
+--_cypress
|    +--  respective subfolders
+--_src
|    +--  respective subfolders (the ones already on README)
```

**Comment by EmanuelGF** [comment]
For the sake of simplicity and brevity, you can only include the integration folder and respective subfolders on the cypress folder because the integration folder is where all the tests are coded. Just realized that now 😁 👍

**Comment by inezabonte** [comment]
Cool. Let me get to it 😊
