### ISSUE TITLE
Deploy the Template

### ISSUE THREAD

**Issue by inezabonte** [EmanuelGF/template-react-ui#26]
**Is your feature request related to a problem? Please describe.**
Currently the template is not deployed. So the user would have to clone it and 
start the application in order to see what the template look like

**Describe the solution you'd like**
It would be nice to have the template deployed on hosting services like
Netlify, Vercel or github pages. So that whoever wants to use it knows what they are getting

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by EmanuelGF** [comment]
@inezabonte that is great idea!
I have my own server but for this case I will try hosting on github pages. 👍

**Comment by EmanuelGF** [comment]
Here is the link : [template-react-ui](https://emanuelgf.github.io/template-react-ui)
@inezabonte do you want to update the readme and get that contribution of the day? 😎

**Comment by inezabonte** [comment]
Sure thing, where would you like me to add it.

**Comment by EmanuelGF** [comment]
> Sure thing, where in the readme would you like me to add it.

I'm thinking before or after the preview images. Or anywhere you think it's better. I'll leave it up to you to decide🙏

**Comment by EmanuelGF** [comment]
You can also add this badge: ![Website](https://img.shields.io/website?down_color=gray&down_message=dead&up_color=green&up_message=online&url=https%3A%2F%2Femanuelgf.github.io%2Ftemplate-react-ui%2F%23%2F)
