### ISSUE TITLE
Better "404 - Page not Found" page

### ISSUE THREAD

**Issue by EmanuelGF** [EmanuelGF/template-react-ui#8]
Create a better design for the  "404 - Page not Found" page (NotFound Component).  
Currently it only displays a h1 with the "404 - Page not Found" text and with no styling... 🤔
The objective is to give it some nice styling so that the 404 page could potentially fit any project created from this template and needing little to no changes.

**Comment by BillNas** [comment]
I would like to give it a try. 💪🏻

**Comment by EmanuelGF** [comment]
@BillNas Thank you for your effort. Let me know if you need any help! 👌👍
